kind: pipeline
type: docker
name: test
#Testing fixed GitHub config! installed runner
steps:
- name: hello
  image: alpine
  commands:
  - echo "Hello from Drone! GitHub config fixed!"
  - pwd
  - ls -la
