kind: pipeline
type: docker
name: test
#Testing runner with direct IP connection!
steps:
- name: hello
  image: alpine
  commands:
  - echo "Hello from Drone! Runner connected via IP!"
  - pwd
  - ls -la
