version: '3.8'

services:
  # Private Internet Access VPN
  pia-vpn:
    image: thrnz/docker-wireguard-pia:latest
    container_name: pia-vpn
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - LOC=auto  # or specific location like 'us_california'
      - USER=${PIA_USER}
      - PASS=${PIA_PASS}
      - LOCAL_NETWORK=192.168.0.0/16,172.16.0.0/12,10.0.0.0/8
      - PORT_FORWARDING=1
      - PORT_PERSIST=1
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=1
    volumes:
      - pia-data:/pia
      - /lib/modules:/lib/modules:ro
    restart: unless-stopped
    networks:
      - media-network

  # QBittorrent (through VPN)
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York  # Change to your timezone
      - WEBUI_PORT=8080
    volumes:
      - qbittorrent-config:/config
      - ./downloads:/downloads
      - ./torrents:/torrents
    ports:
      - "8080:8080"
    network_mode: service:pia-vpn
    depends_on:
      - pia-vpn
    restart: unless-stopped

  # Sonarr (TV Show Management)
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York  # Change to your timezone
    volumes:
      - sonarr-config:/config
      - ./tv:/tv
      - ./downloads:/downloads
    ports:
      - "8989:8989"
    restart: unless-stopped
    networks:
      - media-network

  # Radarr (Movie Management)
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York  # Change to your timezone
    volumes:
      - radarr-config:/config
      - ./movies:/movies
      - ./downloads:/downloads
    ports:
      - "7878:7878"
    restart: unless-stopped
    networks:
      - media-network

  # Lidarr (Music Management)
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York  # Change to your timezone
    volumes:
      - lidarr-config:/config
      - ./music:/music
      - ./downloads:/downloads
    ports:
      - "8686:8686"
    restart: unless-stopped
    networks:
      - media-network

  # Prowlarr (Indexer Manager - Optional but recommended)
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York  # Change to your timezone
    volumes:
      - prowlarr-config:/config
    ports:
      - "9696:9696"
    restart: unless-stopped
    networks:
      - media-network

  # Jellyfin Media Server (Optional - for streaming your media)
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York  # Change to your timezone
    volumes:
      - jellyfin-config:/config
      - ./tv:/data/tvshows
      - ./movies:/data/movies
      - ./music:/data/music
    ports:
      - "8096:8096"
    restart: unless-stopped
    networks:
      - media-network

volumes:
  pia-data:
  qbittorrent-config:
  sonarr-config:
  radarr-config:
  lidarr-config:
  prowlarr-config:
  jellyfin-config:

networks:
  media-network:
    driver: bridge