version: '3.8'

services:
  drone-server:
    image: drone/drone:2
    container_name: drone_server
    ports:
      - "8082:80"
    volumes:
      - ./drone_server_data:/data
    networks:
      - drone-net
    environment:
      - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}
      - DRONE_SERVER_HOST=${DRONE_SERVER_HOST}
      - DRONE_SERVER_PROTO=${DRONE_SERVER_PROTO}
      - DRONE_GITHUB_CLIENT_ID=${DRONE_GITHUB_CLIENT_ID}
      - DRONE_GITHUB_CLIENT_SECRET=${DRONE_GITHUB_CLIENT_SECRET}
      - DRONE_USER_CREATE=${DRONE_USER_CREATE}
      - DRONE_DATABASE_DRIVER=${DRONE_DATABASE_DRIVER}
      - DRONE_DATABASE_DATASOURCE=${DRONE_DATABASE_DATASOURCE}
    restart: unless-stopped

  drone-runner:
    image: drone/drone-runner-docker:1
    container_name: drone_runner
    depends_on:
      - drone-server
    ports:
      - "3000:3000"
    volumes:
      - /run/podman/podman.sock:/var/run/docker.sock
    networks:
      - drone-net
    environment:
      - DRONE_RPC_HOST=localhost:8082
      - DRONE_RPC_PROTO=http
      - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}
      - DRONE_RUNNER_CAPACITY=2
      - DRONE_RUNNER_NAME=podman-runner
      - DRONE_RUNNER_NETWORKS=drone-net
    restart: unless-stopped
    privileged: true

networks:
  drone-net:
    driver: bridge
