#!/bin/bash

echo "🔧 Prowlarr Indexer Proxy Setup Guide"
echo "====================================="
echo ""
echo "📋 Available Proxy Options:"
echo "==========================="
echo ""
echo "✅ SOCKS5 Proxy (Recommended):"
echo "   • Host: pia-vpn"
echo "   • Port: 8388"
echo "   • Username: (leave empty)"
echo "   • Password: (leave empty)"
echo "   • Type: SOCKS5"
echo ""
echo "🌐 HTTP Proxy (Alternative):"
echo "   • Host: pia-vpn"
echo "   • Port: 8118"
echo "   • Username: (leave empty)"
echo "   • Password: (leave empty)"
echo "   • Type: HTTP"
echo ""
echo "📡 Step-by-Step Proxy Setup:"
echo "============================"
echo ""
echo "1. 🔐 Access Prowlarr:"
echo "   • Visit: http://localhost:9696"
echo "   • Login with your credentials"
echo ""
echo "2. ⚙️ Go to Proxy Settings:"
echo "   • Navigate to: Settings → Indexer Proxies"
echo "   • Click 'Add Proxy'"
echo ""
echo "3. 🔧 Configure SOCKS5 Proxy:"
echo "   • Name: PIA VPN SOCKS5"
echo "   • Implementation: SOCKS5"
echo "   • Host: pia-vpn"
echo "   • Port: 8388"
echo "   • Username: (leave empty)"
echo "   • Password: (leave empty)"
echo "   • Enable: Yes"
echo ""
echo "4. 🧪 Test the Proxy:"
echo "   • Click 'Test' button"
echo "   • Should show 'Success' if working"
echo ""
echo "5. 🔗 Assign to Indexers:"
echo "   • Go to Settings → Indexers"
echo "   • Edit each indexer"
echo "   • Under 'Proxy' dropdown, select 'PIA VPN SOCKS5'"
echo "   • Save the indexer"
echo ""
echo "📋 Proxy Benefits:"
echo "=================="
echo "• Bypass Cloudflare DNS blocks"
echo "• Hide your real IP from indexers"
echo "• Access geo-blocked indexers"
echo "• Improve indexer reliability"
echo "• VPN-protected indexer access"
echo ""
echo "🔍 Recommended Indexers with Proxy:"
echo "==================================="
echo "• RARBG (https://rarbg.to)"
echo "• YTS (https://yts.mx)"
echo "• EZTV (https://eztv.re)"
echo "• 1337x (https://1337x.to)"
echo "• ThePirateBay (https://thepiratebay.org)"
echo ""
echo "⚠️ Important Notes:"
echo "=================="
echo "• Use 'pia-vpn' as hostname (not localhost)"
echo "• Leave username/password empty unless required"
echo "• Test each indexer after assigning proxy"
echo "• Some indexers may not work with proxy"
echo "• Monitor indexer health after proxy setup"
echo ""
echo "🌐 Alternative Proxy Options:"
echo "============================"
echo ""
echo "If SOCKS5 doesn't work, try HTTP proxy:"
echo "• Host: pia-vpn"
echo "• Port: 8118"
echo "• Type: HTTP"
echo ""
echo "Or use direct connection (no proxy):"
echo "• Some indexers work better without proxy"
echo "• Test both with and without proxy"
echo ""
echo "🚀 Your indexers will now be VPN-protected!" 