#!/bin/bash

echo "🌐 Static IP Configuration - Complete!"
echo "======================================"
echo ""
echo "✅ All containers now have static IPs for reliable routing"
echo ""
echo "📋 Static IP Assignment:"
echo "======================="
echo "• pia-vpn:      172.19.0.4 (VPN container)"
echo "• transmission: 172.19.0.4 (uses VPN network)"
echo "• prowlarr:     172.19.0.4 (uses VPN network)"
echo "• jackett:      172.19.0.4 (uses VPN network)"
echo "• sonarr:       172.19.0.5:8989"
echo "• radarr:       172.19.0.6:7878"
echo "• lidarr:       172.19.0.7:8686"
echo "• jellyfin:     172.19.0.8:8096"
echo ""
echo "🔧 Service Configurations Updated:"
echo "================================="
echo "✅ *arr services → Transmission: 172.19.0.4:9091"
echo "✅ Prowlarr → Radarr: 172.19.0.6:7878"
echo "✅ All internal routing uses static IPs"
echo ""
echo "🌐 External Access URLs:"
echo "======================="
echo "• Radarr:   http://localhost:7878"
echo "• Sonarr:   http://localhost:8989"
echo "• Lidarr:   http://localhost:8686"
echo "• Prowlarr: http://localhost:9696"
echo "• Transmission: http://localhost:9091/transmission/web/"
echo "• Jellyfin: http://localhost:8096"
echo ""
echo "📋 Prowlarr Configuration Guide:"
echo "==============================="
echo "For Prowlarr → *arr connections, use these URLs:"
echo ""
echo "Radarr:"
echo "• URL: http://172.19.0.6:7878"
echo "• API Key: Get from Radarr Settings → General"
echo ""
echo "Sonarr:"
echo "• URL: http://172.19.0.5:8989"
echo "• API Key: Get from Sonarr Settings → General"
echo ""
echo "Lidarr:"
echo "• URL: http://172.19.0.7:8686"
echo "• API Key: Get from Lidarr Settings → General"
echo ""
echo "🔧 Benefits of Static IPs:"
echo "========================="
echo "• Consistent routing between restarts"
echo "• No DNS resolution issues"
echo "• Reliable service-to-service communication"
echo "• Predictable network topology"
echo "• Easy troubleshooting"
echo ""
echo "⚠️ Important Notes:"
echo "=================="
echo "• All IPs are in 172.19.0.0/16 subnet"
echo "• VPN services share 172.19.0.4"
echo "• *arr services have unique IPs"
echo "• Use IP addresses for internal routing"
echo "• Use localhost for external access"
echo ""
echo "🚀 Your media stack now has reliable, static networking!"
echo ""
echo "📋 Next Steps:"
echo "=============="
echo "1. Configure Prowlarr indexers"
echo "2. Set up Prowlarr → *arr connections"
echo "3. Test RSS feeds and automatic downloads"
echo "4. Add root folders for media"
echo "5. Enjoy your VPN-protected media stack!" 