kind: pipeline
type: docker
name: torrent-media-stack

# Only trigger when files in Torrent/ folder change
trigger:
  paths:
    include:
    - "Torrent/**"
  event:
  - push
  - pull_request

steps:
- name: validate-compose
  image: docker/compose:latest
  commands:
  - cd Torrent
  - docker-compose config
  - echo "✅ Compose file is valid"

- name: check-env-template
  image: alpine:latest
  commands:
  - cd Torrent
  - if [ ! -f .env.example ]; then echo "❌ Missing .env.example"; exit 1; fi
  - echo "✅ Environment template exists"

- name: security-scan
  image: alpine:latest
  commands:
  - cd Torrent
  - echo "🔍 Checking for secrets in compose file..."
  - |
    if grep -q "password\|secret" podman-compose.yml; then
      echo "⚠️  Warning: Potential secrets found in compose file"
    else
      echo "✅ No hardcoded secrets detected"
    fi

- name: deploy-staging
  image: alpine:latest
  commands:
  - echo "🚀 Would deploy to staging environment"
  - cd Torrent
  - echo "podman-compose -f podman-compose.yml up -d"
  when:
    branch:
    - develop
    - feature/*

- name: deploy-production
  image: alpine:latest
  commands:
  - echo "🚀 Deploying to production environment"
  - cd Torrent
  - echo "podman-compose -f podman-compose.yml up -d"
  # Add actual deployment commands here
  when:
    branch:
    - main

- name: notify-success
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack_webhook
    channel: deployments
    template: >
      ✅ **Torrent Media Stack** deployed successfully!
      
      📦 **Services**: QBittorrent, Sonarr, Radarr, Lidarr, Prowlarr, Jellyfin
      🔗 **Branch**: {{build.branch}}
      👤 **Author**: {{build.author}}
      📝 **Commit**: {{truncate build.commit 8}}
  when:
    status: [ success ]

- name: notify-failure
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack_webhook
    channel: deployments
    template: >
      ❌ **Torrent Media Stack** deployment failed!
      
      🔗 **Branch**: {{build.branch}}
      👤 **Author**: {{build.author}}
      📝 **Commit**: {{truncate build.commit 8}}
      🔗 **Build**: {{build.link}}
  when:
    status: [ failure ]

---
kind: secret
name: slack_webhook
data: your_encrypted_slack_webhook_here
