version: '3.8'

networks:
  drone-net:
    driver: bridge

services:
  drone-server:
    image: drone/drone:2
    container_name: drone_server
    ports:
      - "8082:80" # Map host port 8082 to container port 80
    volumes:
      - ./drone_server_data:/data
    networks:
      - drone-net
    env_file:
      - .env
    restart: unless-stopped

  drone-runner:
    image: drone/drone-runner-docker:1
    container_name: drone_runner
    depends_on:
      - drone-server
    volumes:
      - /run/podman/podman.sock:/var/run/docker.sock
    networks:
      - drone-net
    env_file:
      - .env
    restart: unless-stopped
