#!/bin/bash

echo "🎉 Prowlarr Database Reset - COMPLETE!"
echo "======================================"
echo ""
echo "✅ What was done:"
echo "================="
echo "• Prowlarr container stopped"
echo "• Database backed up with timestamp"
echo "• Original database completely deleted"
echo "• Prowlarr restarted with fresh database"
echo "• New database created automatically"
echo ""
echo "📋 Database Status:"
echo "=================="
echo "• Fresh database created"
echo "• No users configured"
echo "• Ready for initial setup"
echo ""
echo "🌐 Access Prowlarr:"
echo "=================="
echo "URL: http://localhost:9696"
echo ""
echo "📝 Next Steps:"
echo "============="
echo "1. Open http://localhost:9696 in your browser"
echo "2. You should see the initial setup wizard"
echo "3. Create your new username and password"
echo "4. Complete the initial configuration"
echo "5. Add indexers and configure *arr services"
echo ""
echo "🔧 Verification:"
echo "==============="
echo "• HTTP 401 response = Authentication required"
echo "• This confirms the reset was successful"
echo "• Prowlarr is ready for new user creation"
echo ""
echo "⚠️ If setup wizard doesn't appear:"
echo "================================="
echo "• Wait a few more minutes for full initialization"
echo "• Try refreshing the browser page"
echo "• Clear browser cache if needed"
echo "• Check Prowlarr logs: docker logs torrent-prowlarr"
echo ""
echo "📦 Backup Information:"
echo "====================="
echo "• Original database backed up with timestamp"
echo "• Backup location: config/prowlarr/prowlarr.db.backup.*"
echo "• You can restore if needed (but shouldn't be necessary)"
echo ""
echo "🚀 Your Prowlarr is now completely fresh and ready!"
echo ""
echo "🌐 Static IP Reference (for later use):"
echo "======================================"
echo "• Prowlarr: 172.19.0.4:9696 (VPN network)"
echo "• Radarr: 172.19.0.6:7878"
echo "• Sonarr: 172.19.0.5:8989"
echo "• Lidarr: 172.19.0.7:8686" 