#!/bin/bash

echo "🔧 Prowlarr-Radarr Connection Fix"
echo "================================="
echo ""
echo "✅ SOLUTION FOUND!"
echo ""
echo "📋 Problem:"
echo "• http://torrent-radarr:7878/ won't resolve in Prowlarr"
echo "• Network isolation between Prowlarr (VPN) and Radarr (media-network)"
echo ""
echo "🌐 Working URLs for Prowlarr → Radarr:"
echo "======================================="
echo ""
echo "✅ PRIMARY SOLUTION:"
echo "• URL: http://172.19.0.6:7878"
echo "• This is Radarr's actual IP address"
echo "• Tested and working (HTTP 401 = connection successful)"
echo ""
echo "📋 Alternative URLs (if needed):"
echo "• http://localhost:7878 (host network)"
echo "• http://radarr:7878 (if DNS resolution works)"
echo ""
echo "🔧 Step-by-Step Setup:"
echo "======================"
echo ""
echo "1. 🔐 Access Prowlarr:"
echo "   • Visit: http://localhost:9696"
echo "   • Login with your credentials"
echo ""
echo "2. ⚙️ Go to Apps Settings:"
echo "   • Navigate to: Settings → Apps"
echo "   • Click 'Add App'"
echo "   • Select 'Radarr'"
echo ""
echo "3. 🔧 Configure Radarr Connection:"
echo "   • Name: Radarr"
echo "   • Prowlarr URL: http://prowlarr:9696"
echo "   • Radarr URL: http://172.19.0.6:7878"
echo "   • API Key: (get from Radarr Settings → General)"
echo "   • Sync Level: Add Only"
echo "   • Categories: Movies (2000, 2010, 2020, etc.)"
echo ""
echo "4. 🧪 Test the Connection:"
echo "   • Click 'Test' button in Prowlarr"
echo "   • Should show 'Success' if working"
echo ""
echo "📋 API Key Location:"
echo "==================="
echo "• Open Radarr: http://localhost:7878"
echo "• Go to: Settings → General"
echo "• Copy the 'API Key' value"
echo "• Paste it into Prowlarr's Radarr configuration"
echo ""
echo "⚠️ Important Notes:"
echo "=================="
echo "• Use IP address (172.19.0.6) for most reliable connection"
echo "• The hostname 'torrent-radarr' won't work due to network isolation"
echo "• Prowlarr is on VPN network, Radarr is on media-network"
echo "• This is the expected behavior for your VPN setup"
echo ""
echo "🚀 Your Prowlarr-Radarr connection should now work!"
echo ""
echo "🌐 Service URLs:"
echo "   • Radarr:   http://localhost:7878"
echo "   • Prowlarr: http://localhost:9696"
echo "   • Radarr IP: http://172.19.0.6:7878" 