#!/bin/bash

echo "🎉 Prowlarr Nuclear Reset - COMPLETE!"
echo "====================================="
echo ""
echo "✅ What was done:"
echo "================="
echo "• Prowlarr container stopped"
echo "• Entire config directory backed up"
echo "• Complete config directory deleted"
echo "• Fresh config directory created"
echo "• Prowlarr restarted with clean slate"
echo "• Database migrations completed successfully"
echo ""
echo "📋 Current Status:"
echo "================="
echo "• Prowlarr is running and accessible"
echo "• Fresh database created"
echo "• No users configured"
echo "• Ready for initial setup"
echo ""
echo "🌐 Access Prowlarr:"
echo "=================="
echo "URL: http://localhost:9696"
echo ""
echo "📝 What you should see:"
echo "======================"
echo "• Prowlarr login page"
echo "• Initial setup wizard"
echo "• Option to create new user"
echo ""
echo "🔧 Verification Results:"
echo "======================"
echo "• HTTP 401 header = Authentication required"
echo "• HTML content returned = Page is loading"
echo "• Database migrations completed = Fresh DB ready"
echo "• Container running = Service is up"
echo ""
echo "📋 Next Steps:"
echo "============="
echo "1. Open http://localhost:9696 in your browser"
echo "2. You should see the Prowlarr login/setup page"
echo "3. Create your new username and password"
echo "4. Complete the initial configuration"
echo "5. Add indexers and configure *arr services"
echo ""
echo "⚠️ If you still can't access the setup:"
echo "======================================"
echo "• Try a different browser"
echo "• Clear browser cache completely"
echo "• Try incognito/private browsing mode"
echo "• Check if any browser extensions are blocking"
echo "• Wait a few more minutes for full initialization"
echo ""
echo "🔧 Alternative access methods:"
echo "============================"
echo "• Try: http://127.0.0.1:9696"
echo "• Try: http://172.19.0.4:9696 (static IP)"
echo "• Check logs: docker logs torrent-prowlarr"
echo ""
echo "📦 Backup Information:"
echo "====================="
echo "• Complete config backed up to: config/prowlarr.backup.*"
echo "• You can restore if needed: cp -r config/prowlarr.backup.* config/prowlarr"
echo ""
echo "🚀 Your Prowlarr is now completely fresh and ready!"
echo ""
echo "🌐 Static IP Reference:"
echo "======================"
echo "• Prowlarr: 172.19.0.4:9696 (VPN network)"
echo "• Radarr: 172.19.0.6:7878"
echo "• Sonarr: 172.19.0.5:8989"
echo "• Lidarr: 172.19.0.7:8686" 