#!/bin/bash

echo "🔧 Radarr-Prowlarr RSS Setup Guide"
echo "=================================="
echo ""
echo "📋 Current Status:"
echo "   ✅ Radarr has Prowlarr configured"
echo "   ✅ RSS and automatic search are enabled"
echo "   ✅ API keys are available"
echo "   ⚠️ Prowlarr has no indexers (needs setup)"
echo ""
echo "🌐 Step 1: Add Indexers to Prowlarr"
echo "===================================="
echo "1. Visit: http://localhost:9696"
echo "2. Login with your credentials"
echo "3. Go to Settings → Indexers"
echo "4. Click 'Add Indexer'"
echo "5. Search for and add these popular indexers:"
echo ""
echo "   🔍 Recommended Indexers:"
echo "   • RARBG (https://rarbg.to)"
echo "   • YTS (https://yts.mx)"
echo "   • EZTV (https://eztv.re)"
echo "   • 1337x (https://1337x.to)"
echo "   • ThePirateBay (https://thepiratebay.org)"
echo ""
echo "   ⚙️ For each indexer:"
echo "   • Leave API key empty (for public indexers)"
echo "   • Enable RSS and Search"
echo "   • Test the indexer"
echo ""
echo "🌐 Step 2: Connect Prowlarr to Radarr"
echo "======================================"
echo "1. In Prowlarr, go to Settings → Apps"
echo "2. Click 'Add App'"
echo "3. Select 'Radarr'"
echo "4. Configure with these settings:"
echo ""
echo "   📋 Radarr Configuration:"
echo "   • Name: Radarr"
echo "   • Prowlarr URL: http://prowlarr:9696"
echo "   • Radarr URL: http://radarr:7878"
echo "   • API Key: (get from Radarr Settings → General)"
echo "   • Sync Level: Add Only"
echo "   • Categories: Movies (2000, 2010, 2020, etc.)"
echo ""
echo "🌐 Step 3: Test RSS Feed"
echo "========================"
echo "1. Visit Radarr: http://localhost:7878"
echo "2. Go to Settings → Indexers"
echo "3. Check that Prowlarr shows as active"
echo "4. Add a movie to your library"
echo "5. Test automatic search"
echo ""
echo "📋 RSS Feed Benefits:"
echo "====================="
echo "• Automatic discovery of new releases"
echo "• Real-time updates from indexers"
echo "• VPN-protected indexer access"
echo "• Centralized indexer management"
echo "• No need to manually search for releases"
echo ""
echo "🚀 After completing these steps, your RSS feed will be active!"
echo ""
echo "🌐 Service URLs:"
echo "   • Radarr:   http://localhost:7878"
echo "   • Prowlarr: http://localhost:9696"
echo "   • Transmission: http://localhost:9091/transmission/web/" 