#!/bin/bash

echo "🔧 Prowlarr Indexer Setup Guide"
echo "==============================="
echo ""
echo "📋 Current Status:"
echo "   ✅ All services are running"
echo "   ✅ Transmission connection fixed"
echo "   ✅ *arr services have Prowlarr configured"
echo "   ⚠️ Prowlarr has 0 indexers (needs setup)"
echo ""
echo "🌐 Access Prowlarr: http://localhost:9696"
echo ""
echo "📝 Step-by-Step Prowlarr Setup:"
echo ""
echo "1. 🔐 Login to Prowlarr:"
echo "   • Visit: http://localhost:9696"
echo "   • Use your new username/password"
echo ""
echo "2. 📡 Add Popular Indexers:"
echo "   • Go to Settings → Indexers"
echo "   • Click 'Add Indexer'"
echo "   • Search for and add these popular indexers:"
echo ""
echo "   🔍 Recommended Indexers:"
echo "   • RARBG (https://rarbg.to)"
echo "   • YTS (https://yts.mx)"
echo "   • EZTV (https://eztv.re)"
echo "   • 1337x (https://1337x.to)"
echo "   • ThePirateBay (https://thepiratebay.org)"
echo ""
echo "3. ⚙️ Indexer Configuration:"
echo "   • For public indexers, leave API key empty"
echo "   • Enable RSS and Search for each indexer"
echo "   • Test each indexer after adding"
echo ""
echo "4. 🔗 Connect to *arr Services:"
echo "   • Go to Settings → Apps"
echo "   • Add your *arr services:"
echo "     - Radarr: http://radarr:7878"
echo "     - Sonarr: http://sonarr:8989"
echo "     - Lidarr: http://lidarr:8686"
echo "   • Use the API keys from each service"
echo ""
echo "5. 🧪 Test the Setup:"
echo "   • Go to Indexers tab"
echo "   • Search for a movie/show"
echo "   • Verify results appear"
echo ""
echo "📋 After completing Prowlarr setup, run:"
echo "   ./fix-prowlarr-indexers-corrected.sh"
echo ""
echo "🌐 Service URLs:"
echo "   • Radarr:   http://localhost:7878"
echo "   • Sonarr:   http://localhost:8989"
echo "   • Lidarr:   http://localhost:8686"
echo "   • Prowlarr: http://localhost:9696"
echo "   • Transmission: http://localhost:9091/transmission/web/"
echo ""
echo "✅ Your VPN-enabled media stack will be fully functional!" 