#!/bin/bash

echo "🎬 Setting up Radarr Root Folders"
echo "================================="

echo ""
echo "📋 Instructions for Radarr Root Folder Setup:"
echo ""
echo "1. Open Radarr: http://localhost:7878"
echo "2. Go to: Settings → Media Management"
echo "3. Click: 'Add Root Folder'"
echo "4. Set Path: /movies"
echo "5. Click: 'Save'"
echo ""
echo "📁 Directory Structure:"
echo "   /movies/"
echo "   ├── Action/"
echo "   ├── Comedy/"
echo "   ├── Drama/"
echo "   ├── Horror/"
echo "   └── [Movie Name]/"
echo "       ├── Movie Name (2025).mkv"
echo "       ├── Movie Name (2025).nfo"
echo "       └── poster.jpg"
echo ""
echo "✅ Verification:"
echo "   • Directory accessible: /movies"
echo "   • Write permissions: ✅"
echo "   • Volume mapping: /mnt/truenas/media/movies → /movies"
echo ""
echo "🎯 Next Steps:"
echo "   1. Add root folder in Radarr UI"
echo "   2. Add your first movie"
echo "   3. Test download functionality"
echo ""
echo "📝 Note: Subfolders like 'Superman (2025)' will be created automatically"
echo "   when you add movies to Radarr." 